services:
  # app:
  #   build:
  #     context: .               
  #     dockerfile: Dockerfile  
  #   container_name: fethcher
  #   environment:
  # - DB_CONNECTION_URL=host=db user=postgres password=postgres dbname=postgres sslmode=disable
  # - ETH_NODE_URL=https://sepolia.infura.io/v3/your_project_id_here
  # - API_PORT=9205
  # - JWT_SECRET=4a03e22b74d3fc8edeff82390dc72f27c0a0bbf4c4e824a9ed15f1612a1c5cef
  #   ports:
  #     - "9205:9205"
  #   networks:
  #     - lime-net
  app-debug:
    image: golang:1.23
    container_name: fethcher
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      - DB_CONNECTION_URL=host=db user=postgres password=postgres dbname=fethcher sslmode=disable
      - ETH_NODE_URL=https://sepolia.infura.io/v3/your_project_id_here
      - API_PORT=9205
      - JWT_SECRET=4a03e22b74d3fc8edeff82390dc72f27c0a0bbf4c4e824a9ed15f1612a1c5cef
    ports:
      - "9205:9205"
    networks:
      - lime-net

  db:
    image: postgres:15
    container_name: feth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fethcher
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lime-net

volumes:
  pgdata:


networks:
  lime-net:
    driver: bridge
