// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"fethcher/internal/repository"
	"sync"
)

type Storage struct {
	GetAllByStub        func(string, any, any) error
	getAllByMutex       sync.RWMutex
	getAllByArgsForCall []struct {
		arg1 string
		arg2 any
		arg3 any
	}
	getAllByReturns struct {
		result1 error
	}
	getAllByReturnsOnCall map[int]struct {
		result1 error
	}
	GetOneByStub        func(string, any, any) error
	getOneByMutex       sync.RWMutex
	getOneByArgsForCall []struct {
		arg1 string
		arg2 any
		arg3 any
	}
	getOneByReturns struct {
		result1 error
	}
	getOneByReturnsOnCall map[int]struct {
		result1 error
	}
	MigrateTableStub        func(...any) error
	migrateTableMutex       sync.RWMutex
	migrateTableArgsForCall []struct {
		arg1 []any
	}
	migrateTableReturns struct {
		result1 error
	}
	migrateTableReturnsOnCall map[int]struct {
		result1 error
	}
	SaveToTableStub        func(any) error
	saveToTableMutex       sync.RWMutex
	saveToTableArgsForCall []struct {
		arg1 any
	}
	saveToTableReturns struct {
		result1 error
	}
	saveToTableReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Storage) GetAllBy(arg1 string, arg2 any, arg3 any) error {
	fake.getAllByMutex.Lock()
	ret, specificReturn := fake.getAllByReturnsOnCall[len(fake.getAllByArgsForCall)]
	fake.getAllByArgsForCall = append(fake.getAllByArgsForCall, struct {
		arg1 string
		arg2 any
		arg3 any
	}{arg1, arg2, arg3})
	stub := fake.GetAllByStub
	fakeReturns := fake.getAllByReturns
	fake.recordInvocation("GetAllBy", []interface{}{arg1, arg2, arg3})
	fake.getAllByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) GetAllByCallCount() int {
	fake.getAllByMutex.RLock()
	defer fake.getAllByMutex.RUnlock()
	return len(fake.getAllByArgsForCall)
}

func (fake *Storage) GetAllByCalls(stub func(string, any, any) error) {
	fake.getAllByMutex.Lock()
	defer fake.getAllByMutex.Unlock()
	fake.GetAllByStub = stub
}

func (fake *Storage) GetAllByArgsForCall(i int) (string, any, any) {
	fake.getAllByMutex.RLock()
	defer fake.getAllByMutex.RUnlock()
	argsForCall := fake.getAllByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) GetAllByReturns(result1 error) {
	fake.getAllByMutex.Lock()
	defer fake.getAllByMutex.Unlock()
	fake.GetAllByStub = nil
	fake.getAllByReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) GetAllByReturnsOnCall(i int, result1 error) {
	fake.getAllByMutex.Lock()
	defer fake.getAllByMutex.Unlock()
	fake.GetAllByStub = nil
	if fake.getAllByReturnsOnCall == nil {
		fake.getAllByReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getAllByReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) GetOneBy(arg1 string, arg2 any, arg3 any) error {
	fake.getOneByMutex.Lock()
	ret, specificReturn := fake.getOneByReturnsOnCall[len(fake.getOneByArgsForCall)]
	fake.getOneByArgsForCall = append(fake.getOneByArgsForCall, struct {
		arg1 string
		arg2 any
		arg3 any
	}{arg1, arg2, arg3})
	stub := fake.GetOneByStub
	fakeReturns := fake.getOneByReturns
	fake.recordInvocation("GetOneBy", []interface{}{arg1, arg2, arg3})
	fake.getOneByMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) GetOneByCallCount() int {
	fake.getOneByMutex.RLock()
	defer fake.getOneByMutex.RUnlock()
	return len(fake.getOneByArgsForCall)
}

func (fake *Storage) GetOneByCalls(stub func(string, any, any) error) {
	fake.getOneByMutex.Lock()
	defer fake.getOneByMutex.Unlock()
	fake.GetOneByStub = stub
}

func (fake *Storage) GetOneByArgsForCall(i int) (string, any, any) {
	fake.getOneByMutex.RLock()
	defer fake.getOneByMutex.RUnlock()
	argsForCall := fake.getOneByArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) GetOneByReturns(result1 error) {
	fake.getOneByMutex.Lock()
	defer fake.getOneByMutex.Unlock()
	fake.GetOneByStub = nil
	fake.getOneByReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) GetOneByReturnsOnCall(i int, result1 error) {
	fake.getOneByMutex.Lock()
	defer fake.getOneByMutex.Unlock()
	fake.GetOneByStub = nil
	if fake.getOneByReturnsOnCall == nil {
		fake.getOneByReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getOneByReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) MigrateTable(arg1 ...any) error {
	fake.migrateTableMutex.Lock()
	ret, specificReturn := fake.migrateTableReturnsOnCall[len(fake.migrateTableArgsForCall)]
	fake.migrateTableArgsForCall = append(fake.migrateTableArgsForCall, struct {
		arg1 []any
	}{arg1})
	stub := fake.MigrateTableStub
	fakeReturns := fake.migrateTableReturns
	fake.recordInvocation("MigrateTable", []interface{}{arg1})
	fake.migrateTableMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) MigrateTableCallCount() int {
	fake.migrateTableMutex.RLock()
	defer fake.migrateTableMutex.RUnlock()
	return len(fake.migrateTableArgsForCall)
}

func (fake *Storage) MigrateTableCalls(stub func(...any) error) {
	fake.migrateTableMutex.Lock()
	defer fake.migrateTableMutex.Unlock()
	fake.MigrateTableStub = stub
}

func (fake *Storage) MigrateTableArgsForCall(i int) []any {
	fake.migrateTableMutex.RLock()
	defer fake.migrateTableMutex.RUnlock()
	argsForCall := fake.migrateTableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Storage) MigrateTableReturns(result1 error) {
	fake.migrateTableMutex.Lock()
	defer fake.migrateTableMutex.Unlock()
	fake.MigrateTableStub = nil
	fake.migrateTableReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) MigrateTableReturnsOnCall(i int, result1 error) {
	fake.migrateTableMutex.Lock()
	defer fake.migrateTableMutex.Unlock()
	fake.MigrateTableStub = nil
	if fake.migrateTableReturnsOnCall == nil {
		fake.migrateTableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.migrateTableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) SaveToTable(arg1 any) error {
	fake.saveToTableMutex.Lock()
	ret, specificReturn := fake.saveToTableReturnsOnCall[len(fake.saveToTableArgsForCall)]
	fake.saveToTableArgsForCall = append(fake.saveToTableArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.SaveToTableStub
	fakeReturns := fake.saveToTableReturns
	fake.recordInvocation("SaveToTable", []interface{}{arg1})
	fake.saveToTableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) SaveToTableCallCount() int {
	fake.saveToTableMutex.RLock()
	defer fake.saveToTableMutex.RUnlock()
	return len(fake.saveToTableArgsForCall)
}

func (fake *Storage) SaveToTableCalls(stub func(any) error) {
	fake.saveToTableMutex.Lock()
	defer fake.saveToTableMutex.Unlock()
	fake.SaveToTableStub = stub
}

func (fake *Storage) SaveToTableArgsForCall(i int) any {
	fake.saveToTableMutex.RLock()
	defer fake.saveToTableMutex.RUnlock()
	argsForCall := fake.saveToTableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Storage) SaveToTableReturns(result1 error) {
	fake.saveToTableMutex.Lock()
	defer fake.saveToTableMutex.Unlock()
	fake.SaveToTableStub = nil
	fake.saveToTableReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) SaveToTableReturnsOnCall(i int, result1 error) {
	fake.saveToTableMutex.Lock()
	defer fake.saveToTableMutex.Unlock()
	fake.SaveToTableStub = nil
	if fake.saveToTableReturnsOnCall == nil {
		fake.saveToTableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveToTableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAllByMutex.RLock()
	defer fake.getAllByMutex.RUnlock()
	fake.getOneByMutex.RLock()
	defer fake.getOneByMutex.RUnlock()
	fake.migrateTableMutex.RLock()
	defer fake.migrateTableMutex.RUnlock()
	fake.saveToTableMutex.RLock()
	defer fake.saveToTableMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Storage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.Storage = new(Storage)
